#!/usr/bin/env python3
"""Screen repositories for a WRITTEN rule about AI-authored contributions.

Why this exists
---------------
2026-08-17 07:03Z: `VeckoTheGecko` closed BOTH of our Parcels PRs (#2824, #2826)
with one line — "This contribution violates our AI policy" — pointing at
docs.parcels-code.org/en/main/development/policies.html.

Read, that page does NOT ban AI. It says you must understand what you commit,
and it points at the repository's own `CLAUDE.md`. That file says:

    Never create issues nor pull requests on the GitHub repository unless
    explicitly instructed

That is the rule we broke, it was published in the repo the whole time, and
nothing in this operation ever looked for it. Two patches were built, opened,
and closed for a reason that was readable before the first line was written.

The screen therefore looks for the agent-instruction files themselves, not for
the word "AI" in prose. A repo that ships `CLAUDE.md` / `AGENTS.md` has written
down how it wants agents to behave; sending it an unsolicited agent-authored PR
without reading that file is the defect.

Verdicts
--------
  BLOCK      an agent-instruction file or prose forbids unsolicited PRs/issues
  MONEY-OUT  the PR is welcome, THE MONEY IS NOT. A maintainer has ruled in the issue
             tracker that bounties are not paid for bot-generated work. Only found with
             --tracker; see MONEY_EXCLUSION_PHRASES and jhipster/generator-jhipster.
  READ       an agent-instruction file exists; its text needs a human read
  POLICY     no agent file, but CONTRIBUTING/README carries an AI/LLM clause
  CLEAR      nothing found

BLOCK is not "never contribute" — it is "do not open anything unprompted."
An explicit written invitation (a maintainer naming a ticket for this account)
is exactly the "explicitly instructed" that such a file asks for.

Usage:
  python3 scripts/ai_policy_screen.py --open-prs      # every repo we have a PR at
  python3 scripts/ai_policy_screen.py --repo owner/name [--repo ...]
  python3 scripts/ai_policy_screen.py --repo owner/name --tracker   # + issue threads
  python3 scripts/ai_policy_screen.py --selftest
"""

from __future__ import annotations

import argparse
import base64
import json
import os
import re
import sys
from html import unescape
import time
import urllib.error
import urllib.parse
import urllib.request

API = "https://api.github.com"

# Files a project writes to tell coding agents how to behave. Order matters only
# for reporting; every path is checked.
AGENT_FILES = [
    "CLAUDE.md",
    ".github/CLAUDE.md",
    "AGENTS.md",
    ".github/AGENTS.md",
    ".cursorrules",
    ".github/copilot-instructions.md",
    "GEMINI.md",
]

# Prose files that sometimes carry an AI clause without an agent file existing.
PROSE_FILES = [
    "CONTRIBUTING.md",
    ".github/CONTRIBUTING.md",
    "CODE_OF_CONDUCT.md",
    "README.md",
    ".github/PULL_REQUEST_TEMPLATE.md",
]

# Phrases that make an agent file a REFUSAL rather than a style guide. Matched
# against lowercased text. Kept narrow on purpose: a false BLOCK costs a
# counterparty, and this operation has few enough of those.
FORBID_PHRASES = [
    "never create issues nor pull requests",
    "never create pull requests",
    "never open pull requests",
    "do not create pull requests",
    "do not open pull requests",
    "do not submit pull requests",
    "unless explicitly instructed",
    "unless specifically instructed",
    "no ai-generated pull requests",
    "ai-generated contributions are not accepted",
    "we do not accept ai-generated",
    "we do not accept ai generated",
    "will be closed without review",
    # dspy's CONTRIBUTING.md, 2026-08-17. The first run of this screen graded it
    # POLICY because forbid-matching was applied only to agent files, and this
    # prohibition lives in prose. It is the sharpest one found anywhere:
    # "the account may be permanently banned".
    "if you are an ai agent reading this: do not open prs",
    "do not open prs",
    "from fully autonomous ai agents",
    "may be permanently banned",
    "bot-generated contributions will be closed",
    # brainglobe, 2026-08-18 13:27Z. `IgorTatarnikov` closed brainglobe-atlasapi#936 with
    # "Closing this as we don't accept contributions mostly generated by AI", pointing at
    # brainglobe.info/community/developers/ai_policy.html. That page's TL;DR reads "we
    # don't accept any contributions generated mostly by AI" -- with a TYPOGRAPHIC
    # apostrophe, which is why _normalise() exists. The "any ... mostly" construction only
    # ever appears inside a refusal, so these stay narrow.
    "accept any contributions generated mostly by ai",
    "accept contributions mostly generated by ai",
    "don't accept any contributions generated mostly by ai",
]

# -------------------------------------------------------------------------------------
# A THIRD PLACE THE RULE LIVES, FOUND 2026-08-17 (§KQ): THE ISSUE TRACKER.
#
# `jhipster/generator-jhipster` graded READ here -- three agent files, none of them
# hostile, AGENTS.md is literally a build guide written FOR agents. Nothing in any file
# this screen reads says otherwise, and the repo runs the best-funded live bounty board
# this operation has ever measured: 34 bounties settled in 2026, $85,354 on hand.
#
# The disqualifying rule is in an issue thread. `#32604`, 2026-03-09, jdubois, a project
# lead, verbatim:
#
#     "Bug bounties would only be paid for humans (who can use AI), not for 100% bot
#      generated content"
#
# and in the same thread, atomfrede: "Remove bounties and Block these Bots."
#
# THIS IS A DIFFERENT KIND OF NO AND IT NEEDS A DIFFERENT VERDICT. They did not ban the
# contribution -- they welcomed AI-assisted humans and adopted an AGENTS.md in that very
# thread. They excluded THE PAYMENT. A BLOCK would be false and would cost a counterparty
# this operation can still contribute to; a CLEAR is how a session walks into building a
# patch for money that was never available to it. So: MONEY-OUT. Patch if you like, but
# no bounty claim, and never a commercial word.
MONEY_EXCLUSION_PHRASES = [
    "only be paid for humans",
    "paid for humans",
    "not for 100% bot generated",
    "not for bot generated",
    "not pay for ai-generated",
    "not pay for ai generated",
    "bounties are for humans",
    "no bounties for ai",
    "block these bots",
    "ban these bots",
    "ai spam submissions",
]

# Where in the tracker to look. Searching every issue is not affordable and not needed:
# a statement like this is always made ON a thread about bounties, bots or AI spam.
MONEY_ISSUE_QUERIES = ["bounty AI", "bounty bot", "AI spam", "AI generated pull requests"]

# Weaker signals in prose: enough to flag for a human read, never to BLOCK.
AI_CLAUSE_PHRASES = [
    "ai policy",
    "use of ai",
    "ai-generated",
    "ai generated",
    "large language model",
    "llm-generated",
    "generative ai",
    "chatgpt",
    "copilot-generated",
]


def _token() -> str:
    for key in ("GITHUB_CLASSIC_PAT", "GITHUB_TOKEN", "GH_TOKEN"):
        val = os.environ.get(key)
        if val:
            return val
    return ""


def _get(path: str, token: str = "", retries: int = 2):
    """GET an API path. Returns parsed JSON, or None on 404."""
    url = path if path.startswith("http") else API + path
    req = urllib.request.Request(url)
    req.add_header("Accept", "application/vnd.github+json")
    if token:
        req.add_header("Authorization", "token " + token)
    for attempt in range(retries + 1):
        try:
            with urllib.request.urlopen(req, timeout=30) as resp:
                return json.loads(resp.read().decode("utf8", "replace"))
        except urllib.error.HTTPError as exc:
            if exc.code == 404:
                return None
            if exc.code in (403, 429) and attempt < retries:
                time.sleep(3 * (attempt + 1))
                continue
            raise
        except urllib.error.URLError:
            if attempt < retries:
                time.sleep(2)
                continue
            raise
    return None


def _normalise(text: str) -> str:
    """Fold the punctuation a docs generator emits back to what the phrase lists type.

    brainglobe's policy says "we don’t accept ..." with U+2019, and every phrase in
    this file is typed with an ASCII apostrophe. A rule that is published, findable and
    unmatched because of a smart quote is the same defect as not looking at all.
    """
    for src, dst in (("’", "'"), ("‘", "'"), ("“", '"'),
                     ("”", '"'), ("–", "-"), ("—", "-"),
                     (" ", " ")):
        text = text.replace(src, dst)
    return re.sub(r"\s+", " ", text)


def _visible_text(html: str) -> str:
    """Strip a docs page down to the prose a maintainer would read."""
    html = re.sub(r"<(script|style|nav|footer)\b.*?</\1>", " ", html, flags=re.S | re.I)
    return _normalise(unescape(re.sub(r"<[^>]+>", " ", html)))


def _get_url(url: str, timeout: int = 30) -> str | None:
    """Plain GET of a documentation page. None on any failure -- the caller reports it."""
    try:
        req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            return resp.read().decode("utf8", "replace")
    except Exception:
        return None


# A FOURTH PLACE THE RULE LIVES, FOUND 2026-08-18: THE PROJECT'S DOCUMENTATION SITE.
#
# This screen was built after Parcels, whose real rule turned out to be in the repo -- so
# it reads repo files and nothing else. `brainglobe/brainglobe-atlasapi` graded CLEAR by
# every one of those files, and on 2026-08-18 a maintainer closed our PR #936 citing a
# policy page on brainglobe.info. Nothing in the repository says it. The screen looked in
# the wrong place for the second time in two days (the first was the Filigran CLA).
#
# The site is reachable in TWO requests and no crawl: the repo's own `homepage` field
# gives the origin, and the origin's `sitemap.xml` -- which documentation generators
# publish as a matter of course -- names the policy page outright. 365 URLs, one hit.
SITE_POLICY_PAT = re.compile(r"ai[-_]?polic|ai[-_]?contribut", re.I)

# An exact filename, not merely a path containing the words. Ranking by raw URL length
# picked `/deep/nested/ai-policy-archive.html` over `/community/developers/ai_policy.html`
# because the archive URL is one character shorter -- caught by the selftest fixture, not
# in the wild. The live policy page is always the one NAMED for the policy.
SITE_POLICY_EXACT = re.compile(r"^ai[-_]?(polic\w*|contributions?)$", re.I)


def _policy_rank(url: str) -> tuple:
    """Sort key: an exactly-named page first, then the shallowest, then the shortest."""
    path = urllib.parse.urlsplit(url).path
    stem = path.rsplit("/", 1)[-1].rsplit(".", 1)[0]
    return (0 if SITE_POLICY_EXACT.match(stem) else 1, path.count("/"), len(url))


def site_policy(repo: str, token: str = "") -> tuple[dict, str]:
    """The project's own docs-site AI policy, if it publishes one.

    -> ({url: text}, note). Two GETs at most. A failure is returned as a NOTE rather than
    swallowed: an absence this screen cannot distinguish from "site unreachable" is the
    exact shape of finding this operation has already been burned by, so it is printed.
    """
    doc = _get(f"/repos/{repo}", token)
    home = (doc or {}).get("homepage") or ""
    if not home.startswith("http"):
        return {}, "no homepage on the repo"
    parts = urllib.parse.urlsplit(home)
    sitemap = f"{parts.scheme}://{parts.netloc}/sitemap.xml"
    raw = _get_url(sitemap)
    if raw is None:
        return {}, f"UNREAD: {sitemap} did not answer -- a site policy could not be ruled out"
    locs = re.findall(r"<loc>([^<]+)</loc>", raw)
    hits = sorted((u for u in locs if SITE_POLICY_PAT.search(urllib.parse.urlsplit(u).path)),
                  key=_policy_rank)
    if not hits:
        return {}, f"{len(locs)} sitemap URLs, no AI-policy page"
    page = _get_url(hits[0])
    if page is None:
        return {}, f"UNREAD: {hits[0]} did not answer -- it IS an AI policy page, read it by hand"
    return {hits[0]: _visible_text(page)}, f"read {hits[0]}"


def fetch_text(repo: str, path: str, token: str = "") -> str | None:
    """Return a repo file's text, or None if it is absent."""
    doc = _get(f"/repos/{repo}/contents/{path}", token)
    if not isinstance(doc, dict) or not doc.get("content"):
        return None
    try:
        return base64.b64decode(doc["content"]).decode("utf8", "replace")
    except Exception:
        return None


def classify(agent_hits: dict, prose_hits: dict,
             tracker_hits: dict | None = None) -> tuple[str, list[str]]:
    """Decide a verdict from what was found. Pure — the selftest drives it.

    A forbid clause counts wherever it is written. The first version of this
    function only forbid-matched agent files, and graded `stanfordnlp/dspy`
    POLICY when its CONTRIBUTING.md said "do not open PRs" and threatened a
    permanent ban — the single strongest prohibition in the whole sweep, missed
    because of where it lived rather than what it said.

    ORDER MATTERS AND IT IS NOT ALPHABETICAL. BLOCK outranks MONEY-OUT: a repo that
    forbids the pull request has settled the payment question too, and reporting
    "you may patch but not bill" about a repo that does not want the patch would be
    worse than useless. MONEY-OUT outranks READ for the mirror-image reason — the
    friendly agent file is exactly what makes the trap.
    """
    reasons: list[str] = []
    for path, text in sorted({**prose_hits, **agent_hits}.items()):
        low = _normalise(text).lower()
        for phrase in FORBID_PHRASES:
            if phrase in low:
                reasons.append(f"{path}: {phrase!r}")
    if reasons:
        return "BLOCK", reasons
    money: list[str] = []
    for where, text in sorted((tracker_hits or {}).items()):
        low = _normalise(text).lower()
        for phrase in MONEY_EXCLUSION_PHRASES:
            if phrase in low:
                money.append(f"{where}: {phrase!r}")
    if money:
        return "MONEY-OUT", money
    if agent_hits:
        return "READ", [f"{p}: agent-instruction file present" for p in sorted(agent_hits)]
    for path, text in sorted(prose_hits.items()):
        low = _normalise(text).lower()
        for phrase in AI_CLAUSE_PHRASES:
            if phrase in low:
                reasons.append(f"{path}: {phrase!r}")
    if reasons:
        return "POLICY", reasons
    return "CLEAR", []


def tracker_statements(repo: str, token: str = "", max_issues: int = 8) -> dict:
    """Issue threads where a maintainer may have ruled on paying bots.

    BOUNDED ON PURPOSE. Reading every issue is unaffordable and unnecessary: a ruling
    like this is always made ON a thread about bounties, bots or AI spam, so the search
    queries find it or nothing does. A failed search returns {} and the caller degrades
    to the file-only verdict — it must never manufacture a CLEAR out of a rate limit,
    which is why the empty case is reported rather than merged into the answer.
    """
    out: dict[str, str] = {}
    seen: set[int] = set()
    for query in MONEY_ISSUE_QUERIES:
        q = urllib.parse.quote(f"repo:{repo} {query}")
        doc = _get(f"/search/issues?q={q}&per_page={max_issues}", token) or {}
        for item in (doc.get("items") or [])[:max_issues]:
            num = item.get("number")
            if num in seen:
                continue
            seen.add(num)
            out[f"issue #{num} (title)"] = item.get("title") or ""
            out[f"issue #{num} (body)"] = item.get("body") or ""
            for c in _get(f"/repos/{repo}/issues/{num}/comments?per_page=100", token) or []:
                out[f"issue #{num} comment by {c['user']['login']}"] = c.get("body") or ""
    return out


class RepoUnreadable(Exception):
    """The repository itself could not be read, so NOTHING can be concluded about it.

    2026-08-18. `--repo sujeito-operator/definitely-not-a-real-repo-xyz` graded **CLEAR,
    rc=0**. Every file fetch 404s, `site_policy` finds no homepage, `classify({}, {})`
    reads "nothing found" and returns CLEAR — the screen said "no policy problem" about a
    repository it had never reached. That is the third time in three days a screen here
    answered a question it had not looked at: the CLA screen read the wrong file, the AI
    screen read repo files and not the docs site, and this one reads a repo that is not
    there.

    It matters because §ME-6 makes a CLEAR the permission slip for the first line of any
    new patch. A renamed org, a typo, a repo gone private, or a dead PAT all produce the
    same silent CLEAR — the absence of a policy is indistinguishable from the absence of a
    repository unless somebody asks. So we ask, in one extra call, before believing any
    verdict about it.
    """


def repo_is_readable(repo: str, token: str = "") -> bool:
    """One call to /repos/<repo>. False means every file 404 below is meaningless."""
    return _get(f"/repos/{repo}", token) is not None


def screen(repo: str, token: str = "", read_tracker: bool = False) -> dict:
    if not repo_is_readable(repo, token):
        raise RepoUnreadable(
            f"{repo}: /repos/{repo} is not readable (404, private, or bad token) — "
            "no verdict is possible and CLEAR would be a lie")
    agent_hits, prose_hits = {}, {}
    for path in AGENT_FILES:
        text = fetch_text(repo, path, token)
        if text is not None:
            agent_hits[path] = text
    for path in PROSE_FILES:
        text = fetch_text(repo, path, token)
        if text is not None:
            prose_hits[path] = text
    site_hits, site_note = site_policy(repo, token)
    prose_hits.update(site_hits)
    tracker_hits = tracker_statements(repo, token) if read_tracker else {}
    verdict, reasons = classify(agent_hits, prose_hits, tracker_hits)
    return {
        "repo": repo,
        "verdict": verdict,
        "reasons": reasons,
        "agent_files": sorted(agent_hits),
        "tracker_read": bool(read_tracker),
        "tracker_sources": len(tracker_hits),
        "site": site_note,
        "site_pages": sorted(site_hits),
    }


def open_pr_repos(token: str) -> list[str]:
    q = "author:sujeito-operator+type:pr+state:open"
    doc = _get(f"/search/issues?q={q}&per_page=100", token) or {}
    seen, out = set(), []
    for item in doc.get("items", []):
        repo = item["repository_url"].split("/repos/")[1]
        if repo not in seen:
            seen.add(repo)
            out.append(repo)
    return out


def selftest() -> int:
    fails = 0

    def check(name, got, want):
        nonlocal fails
        if got != want:
            fails += 1
            print(f"  FAIL {name}: got {got!r} want {want!r}")

    # The case that paid for this file: Parcels' real CLAUDE.md.
    parcels = (
        "## GitHub Interaction Guidelines\n"
        "- **NEVER impersonate the user on GitHub**\n"
        "- Never create issues nor pull requests on the GitHub repository unless\n"
        "  explicitly instructed\n"
    )
    v, r = classify({"CLAUDE.md": parcels}, {})
    check("parcels verdict", v, "BLOCK")
    check("parcels reason count", len(r) >= 1, True)

    # An agent file that is only a style guide must NOT block a counterparty.
    style = "# AGENTS.md\nRun `make fmt` before committing. Prefer small diffs.\n"
    check("style guide", classify({"AGENTS.md": style}, {})[0], "READ")

    # ---------------------------------------------------------------------------------
    # 2026-08-18: the docs-site source. brainglobe-atlasapi graded CLEAR on every repo
    # file and a maintainer closed our PR citing brainglobe.info. These four pin the
    # whole path: the sentence, the smart quote, the sitemap pick, and the false-block.
    BG = ("BrainGlobe policy on contributions using AI TL;DR While we encourage, and are "
          "very grateful for, contributions to our software, we don\u2019t accept any "
          "contributions generated mostly by AI.")
    v, r = classify({}, {"https://brainglobe.info/community/developers/ai_policy.html": BG})
    check("brainglobe site policy blocks", v, "BLOCK")
    check("brainglobe reason names the page", any("brainglobe.info" in x for x in r), True)

    # The smart quote is the whole reason _normalise exists: with a straight apostrophe
    # this string already matched, and the live page does not use one.
    check("the typographic apostrophe is folded", "don't" in _normalise(BG).lower(), True)
    check("normalise leaves the refusal matchable",
          "accept any contributions generated mostly by ai" in _normalise(BG).lower(), True)

    # A PERMISSIVE AI policy must NOT be blocked. This is the expensive direction: a
    # project that publishes a welcoming policy is a better counterparty than average,
    # and blocking it would cost exactly the repos most worth contributing to.
    OK = ("Our AI policy: we welcome AI-assisted contributions provided you have read and "
          "understood the code you submit, and you say so in the pull request.")
    check("a permissive site policy is a flag, not a block",
          classify({}, {"https://x.example/ai_policy.html": OK})[0], "POLICY")

    # The sitemap pick: the right page out of a realistic mixed list, shortest first.
    sm = ("<urlset><loc>https://x.example/blog/index.html</loc>"
          "<loc>https://x.example/community/developers/ai_policy.html</loc>"
          "<loc>https://x.example/deep/nested/ai-policy-archive.html</loc></urlset>")
    import re as _re, urllib.parse as _up
    locs = _re.findall(r"<loc>([^<]+)</loc>", sm)
    hits = sorted((u for u in locs if SITE_POLICY_PAT.search(_up.urlsplit(u).path)),
                  key=_policy_rank)
    check("sitemap finds the policy page", len(hits), 2)
    check("sitemap prefers the exactly-named page over a shorter incidental one",
          hits[0].endswith("/ai_policy.html"), True)
    check("sitemap ignores unrelated pages", any("blog" in h for h in hits), False)

    # _visible_text must not let markup or nav chrome reach the matcher.
    html = "<nav>AI policy</nav><p>we don\u2019t accept any contributions generated mostly by AI</p>"
    vis = _visible_text(html)
    check("visible text drops nav chrome", "AI policy" in vis, False)
    check("visible text keeps the rule",
          "accept any contributions generated mostly by ai" in vis.lower(), True)

    # Prose-only AI clause is a flag, never a block.
    check(
        "prose clause",
        classify({}, {"CONTRIBUTING.md": "We ask that AI-generated code be disclosed."})[0],
        "POLICY",
    )

    # Nothing found is CLEAR.
    check("clear", classify({}, {"README.md": "A Go library for widgets."})[0], "CLEAR")

    # Case-insensitivity: the phrase list is lowercase, the input may not be.
    check(
        "case fold",
        classify({"CLAUDE.md": "DO NOT OPEN PULL REQUESTS."}, {})[0],
        "BLOCK",
    )

    # An agent file wins over prose: BLOCK is not downgraded by a clean README.
    check(
        "agent beats prose",
        classify({"CLAUDE.md": parcels}, {"README.md": "hello"})[0],
        "BLOCK",
    )

    # Empty-but-present agent file is READ, not CLEAR — presence is the signal.
    check("empty agent file", classify({"AGENTS.md": ""}, {})[0], "READ")

    # ---------------------------------------------------------------- MONEY-OUT
    # THE REGRESSION THAT PAID FOR THE THIRD SOURCE. jhipster/generator-jhipster ships
    # three agent files and all three are friendly -- AGENTS.md is a build guide written
    # FOR agents. On files alone this repo reads READ, and a session read it that way and
    # started costing out a bounty. The rule is in issue #32604, and it is verbatim.
    jh_agents = (
        "# AI agent instructions for generator-jhipster\n"
        "Install: `npm ci`. Build: `npm run build`. Tests required for every bug fix.\n"
    )
    check("jhipster on files alone", classify({"AGENTS.md": jh_agents}, {})[0], "READ")

    jh_tracker = {
        "issue #32604 (title)": "Remove bounties from outdated blueprint PRs due to AI spam submissions",
        "issue #32604 comment by jdubois": (
            "Yes, I'm seeing this too, and we need to act.... I'll put it in our mailing "
            "list for discussion:\n- Bug bounties would only be paid for humans (who can "
            "use AI), not for 100% bot generated content\n- Should we ban bots from "
            "contributing? I'm all for AI to make us more productive"),
        "issue #32604 comment by atomfrede": "Remove bounties and Block these Bots.",
    }
    v, r = classify({"AGENTS.md": jh_agents}, {}, jh_tracker)
    check("jhipster with tracker", v, "MONEY-OUT")
    check("jhipster cites the thread", any("#32604" in x for x in r), True)

    # MONEY-OUT MUST NOT SWALLOW A BLOCK. A repo that forbids the PR has settled the
    # payment question; telling a session "you may patch but not bill" would be worse
    # than useless there.
    check("block outranks money-out",
          classify({"CLAUDE.md": parcels}, {}, jh_tracker)[0], "BLOCK")

    # ...AND IT MUST OUTRANK READ, because the friendly agent file is what makes the trap.
    check("money-out outranks read",
          classify({"AGENTS.md": style}, {}, jh_tracker)[0], "MONEY-OUT")

    # A tracker that was not read, or that returned nothing, must not change the verdict
    # and must never manufacture a MONEY-OUT out of an empty search.
    check("tracker absent", classify({"AGENTS.md": style}, {}, None)[0], "READ")
    check("tracker empty", classify({"AGENTS.md": style}, {}, {})[0], "READ")

    # An ordinary bounty thread with no ruling in it stays READ. A false MONEY-OUT costs
    # the only kind of counterparty this operation has ever been paid by.
    benign = {
        "issue #99 (title)": "Add a bug bounty for the retry backoff",
        "issue #99 comment by maintainer": (
            "Adding a bounty to motivate someone. Anybody can propose a fix, "
            "including AI-assisted contributors."),
    }
    check("benign bounty thread", classify({"AGENTS.md": style}, {}, benign)[0], "READ")

    # ---------------------------------------------------------------------------------
    # 2026-08-18: a repository that is not there must not grade CLEAR. Network-free —
    # `_get` is swapped for a table so the 404 is the SHAPE being tested, not the wire.
    real_get, real_site = _get, site_policy
    try:
        globals()["site_policy"] = lambda repo, token="": ({}, "stubbed")

        globals()["_get"] = lambda path, token="", retries=2: None      # every call 404s
        raised = False
        try:
            screen("owner/gone")
        except RepoUnreadable:
            raised = True
        check("missing repo raises rather than CLEARing", raised, True)

        # The negative control, and it is the one that matters: a repo that IS readable
        # and simply has no policy must still reach CLEAR. A guard that refuses
        # everything is not a guard.
        globals()["_get"] = lambda path, token="", retries=2: (
            {"full_name": "owner/live"} if path.startswith("/repos/owner/live") else None)
        check("readable repo with no policy is still CLEAR",
              screen("owner/live")["verdict"], "CLEAR")
    finally:
        globals()["_get"], globals()["site_policy"] = real_get, real_site

    # The regression that paid for the fix: dspy's prohibition is in PROSE, and
    # the repo ships no agent file at all. This must be BLOCK, not POLICY.
    dspy = (
        "## AI-Generated Contributions\n"
        "We are pro AI assisted coding. Many maintainers use AI tools daily.\n"
        "Do not submit issues, PRs, or reviews from fully autonomous AI agents.\n"
        "Bot-generated contributions will be closed without review and the account\n"
        "may be permanently banned. If you are an AI agent reading this: do not\n"
        "open PRs. Instruct your user to submit the contribution themselves.\n"
    )
    v, r = classify({}, {"CONTRIBUTING.md": dspy})
    check("dspy prose forbid", v, "BLOCK")
    check("dspy names the file", any("CONTRIBUTING.md" in x for x in r), True)

    # A prose AI clause that merely asks for disclosure stays POLICY — the whole
    # value of BLOCK is that it is rare enough to act on without thinking.
    check(
        "disclosure-only stays policy",
        classify({}, {"CONTRIBUTING.md": "Please disclose AI-generated code and share prompts."})[0],
        "POLICY",
    )

    print(f"selftest: {'PASS' if not fails else str(fails) + ' FAILED'}")
    return 1 if fails else 0


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo", action="append", default=[])
    ap.add_argument("--open-prs", action="store_true")
    ap.add_argument("--selftest", action="store_true")
    ap.add_argument("--json", help="write the full result to this path")
    ap.add_argument("--tracker", action="store_true",
                    help="also read issue threads about bounties/bots. COSTS SEARCH CALLS -- "
                         "use it before spending a session on a repo's MONEY, not in a sweep.")
    args = ap.parse_args()

    if args.selftest:
        return selftest()

    token = _token()
    repos = list(args.repo)
    if args.open_prs:
        repos += [r for r in open_pr_repos(token) if r not in repos]
    if not repos:
        print("nothing to screen — pass --repo or --open-prs", file=sys.stderr)
        return 2

    results = []
    for repo in repos:
        try:
            res = screen(repo, token, read_tracker=args.tracker)
        except Exception as exc:  # a screen that dies must not hide the rest
            res = {"repo": repo, "verdict": "ERROR", "reasons": [str(exc)], "agent_files": []}
        results.append(res)
        files = ",".join(res["agent_files"]) or "-"
        print(f"{res['verdict']:7s} {repo:45s} {files}")
        for reason in res["reasons"][:3]:
            print(f"          {reason}")

    counts: dict[str, int] = {}
    for res in results:
        counts[res["verdict"]] = counts.get(res["verdict"], 0) + 1
    print("\n" + "  ".join(f"{k}={v}" for k, v in sorted(counts.items())))

    if args.json:
        with open(args.json, "w") as handle:
            json.dump(results, handle, indent=2)
        print(f"wrote {args.json}")
    # An ERROR row is not a verdict. Returning 0 with one in the table is how a sweep
    # gets read as "all clear" -- see RepoUnreadable.
    return 1 if counts.get("ERROR") else 0


if __name__ == "__main__":
    sys.exit(main())
